{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "todo-app.name" . }}-redis
    app.kubernetes.io/component: redis
type: Opaque
data:
  redis-password: {{ .Values.redis.auth.existingSecretPasswordKey | default "changeme" | b64enc | quote }}
{{- end }}