{{- if .Values.reminderService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-reminder-service-svc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "todo-app.name" . }}-reminder-service
    app.kubernetes.io/component: reminder-service
spec:
  type: {{ .Values.reminderService.service.type }}
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "todo-app.name" . }}-reminder-service
  ports:
  - name: http
    port: {{ .Values.reminderService.service.port }}
    targetPort: 8003
{{- end }}